In [2]:
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_excel('Bank_Personal_Loan_Modelling.xlsx')
#data.head(18)

In [3]:
#data.info()
#data.describe()
X= data.drop(['CreditCard'], axis=1)
################ Does the customer uses a credit card issued by UniversalBank?
y = data['CreditCard']
#X.info()


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import tree ,metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=0) 

In [7]:
#DecisionTreeClassifier
model =tree.DecisionTreeClassifier(criterion='entropy',random_state=20)
model.fit(X_train,y_train)
y_predict=model.predict(X_test)
print(y_predict)
count_misclassified = (y_test != y_predict).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(y_test, y_predict)
print('Accuracy: {:.2f}'.format(accuracy))
print(classification_report(y_test,y_predict))

[1 1 0 ... 1 0 1]
Misclassified samples: 562
Accuracy: 0.63
             precision    recall  f1-score   support

          0       0.74      0.72      0.73      1055
          1       0.38      0.40      0.39       445

avg / total       0.63      0.63      0.63      1500



In [8]:
#import pydotplus 
#d_tree = tree.DecisionTreeClassifier()
#d_tree.fit(X_scaled, y)

#dot_data = tree.export_graphviz(d_tree,
#                                out_file=None,
#                               filled=True,
#                             
#rounded=True,
#                               special_characters=True)  
#graph = pydotplus.graph_from_dot_data(dot_data)  

#from IPython.display import Image 
#Image(graph.create_png())

In [10]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10, criterion='entropy')
model.fit(X_train,y_train)
y_predict = model.predict(X_test)
print(y_predict)
count_misclassified = (y_test != y_predict).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(y_test, y_predict)
print('Accuracy: {:.2f}'.format(accuracy))
print(classification_report(y_test,y_predict))

[1 0 0 ... 0 0 0]
Misclassified samples: 436
Accuracy: 0.71
             precision    recall  f1-score   support

          0       0.73      0.93      0.82      1055
          1       0.53      0.19      0.28       445

avg / total       0.67      0.71      0.66      1500



C:\Users\pauls\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [11]:
#GaussianNB
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print(y_predict)
count_misclassified = (y_test != y_predict).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(y_test, y_predict)
print('Accuracy: {:.2f}'.format(accuracy))
print(classification_report(y_test,y_predict))

[0 0 0 ... 0 0 0]
Misclassified samples: 386
Accuracy: 0.74
             precision    recall  f1-score   support

          0       0.74      0.99      0.84      1055
          1       0.86      0.16      0.27       445

avg / total       0.77      0.74      0.67      1500

